import type { DemoTurn, Locale, SceneImageSubject } from '../types'

interface Variant {
  zhMatch: string[]
  enMatch: string[]
  zh: string
  en: string
  prompt: string
  subject?: SceneImageSubject
}

function stage(
  locale: Locale,
  variants: [Variant, Variant, Variant],
  sharedZh: string,
  sharedEn: string,
  choicesZh: [string, string, string],
  choicesEn: [string, string, string],
): DemoTurn[] {
  const zh = locale === 'zh'
  const choices = (zh ? choicesZh : choicesEn).map((choice) => `"${choice}"`).join('|')
  return variants.map((variant) => ({
    match: zh ? variant.zhMatch : variant.enMatch,
    imagePrompt: variant.prompt,
    imageSubject: variant.subject ?? 'player',
    content: `${zh ? variant.zh : variant.en}\n${zh ? sharedZh : sharedEn}\n[choices: ${choices}]`,
  }))
}

export function buildBeforeWeGetHomeCampaign(locale: Locale): DemoTurn[] {
  return [
    ...stage(locale, [
      { zhMatch: ['干燥后巷'], enMatch: ['dry service alley'], zh: '你和阿禾沿早餐铺后的窄巷赶到仁和医院，少淹了两条街，却在塌墙前合力抬开一辆婴儿车。', en: 'You and Ahe take the dry service alley to Renhe Hospital, avoiding two flooded streets but stopping to lift a stroller past a collapsed wall.', prompt: 'the same player protagonist and an orange-jacket delivery rider lifting a stroller past a collapsed wall outside a rain-soaked city hospital at night, grounded disaster drama, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['烟呛', '简单处理'], enMatch: ['first aid', 'smoke'], zh: '你先替被烟呛到的人冲洗眼睛。迟到的七分钟换来一句关键证词：林岚搀着小宇去了仁和医院。', en: 'You rinse smoke from the evacuees’ eyes. Seven lost minutes buy one precise statement: Lin Lan supported Xiaoyu toward Renhe Hospital.', prompt: 'the same player protagonist giving practical first aid beneath a blank market awning in hard rain, orange-jacket rider beside evacuated residents, humane contemporary disaster scene, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['骑行标记', '姐姐'], enMatch: ['route marks', 'sister'], zh: '阿禾在排水管背面找到姐姐常用的三道胶带记号。它们也指向仁和医院，你们第一次确认两条寻亲路线重合。', en: 'Ahe finds her sister’s three strips of route tape behind a drainpipe. They also point to Renhe Hospital; for the first time, both family searches share one road.', prompt: 'Ahe the distinct orange-jacket delivery rider discovering three blank colored tape marks beneath a drainpipe while the player protagonist holds a flashlight, wet market alley, 4:5 portrait, no letters, no text, no UI' },
    ], `[map_update: new_location="仁和医院 · 急诊入口" connected_to="旧市场" detail="停电后的急诊入口由车灯和手电照明，伤员沿雨棚排队" lore="城市东区仍在运作的少数救治点，也是官方转移名单最后一次人工汇总处" facts="家人来过医院|阿禾仍同行"]
[fact: id="hospital-reached" value="true"]
[clock: value="周二 · 00:36"]
[state: value="在急诊入口找到林岚与小宇的去向"]`, `[map_update: new_location="Renhe Hospital · Emergency Entrance" connected_to="Old Market" detail="Car headlights and flashlights illuminate the powerless emergency entrance while casualties queue beneath awnings" lore="One of the last functioning treatment points in the east district and the final hand-compiled transfer list" facts="Family came to the hospital|Ahe is still travelling with the player"]
[fact: id="hospital-reached" value="true"]
[clock: value="Tuesday · 00:36"]
[state: value="Find where Lin Lan and Xiaoyu went after reaching emergency"]`, ['先帮护士把担架送进大厅', '直奔手写转移名单', '用仅剩的信号拨打母亲电话'], ['Help the nurse carry a stretcher inside', 'Go straight to the handwritten transfer list', 'Use the weak signal to call Mother']),

    ...stage(locale, [
      { zhMatch: ['担架', '护士'], enMatch: ['stretcher', 'nurse'], zh: '你把担架抬过失去电力的自动门。护士周岚认出小宇的红色书包：他只做了简单包扎，没有住院。', en: 'You carry the stretcher through dead automatic doors. Nurse Zhoulan recognizes Xiaoyu’s red backpack: he received a bandage but was not admitted.', prompt: 'the same player protagonist carrying a stretcher through a powerless hospital entrance, tired nurse Zhoulan guiding the way, orange-jacket rider behind, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['转移名单'], enMatch: ['transfer list'], zh: '你在潮湿名单上逐行寻找。林岚和小宇没有正式登记，但“红书包、右膝擦伤”旁画着去体育馆的箭头。', en: 'You search the damp list line by line. Lin Lan and Xiaoyu were never formally registered, but a blank mark beside “red backpack, right knee” points toward the stadium.', prompt: 'the same player protagonist examining a damp blank transfer sheet under a flashlight while rain enters a powerless hospital lobby, 4:5 portrait, absolutely no readable marks, no text, no UI' },
      { zhMatch: ['拨打母亲', '电话'], enMatch: ['call Mother', 'weak signal'], zh: '电话只接通两秒。你听见小宇咳嗽和体育馆广播的回声，随后电量又掉了一格。', en: 'The call connects for two seconds. You hear Xiaoyu cough and the echo of a stadium announcement before the battery drops again.', prompt: 'the same player protagonist listening to a phone in a dark hospital lobby as a brief signal connects, face clear, Ahe secondary and distinct, 4:5 portrait, blank phone screen, no writing, no text, no UI' },
    ], `[character_update: character_id="zhoulan-nurse" character="周岚" role="仁和医院护士" detail="连续工作十一个小时，正在组织最后一批胰岛素转运" lore="住在河湾学校附近，熟悉体育馆与学校之间的避险路线" vitality="63" stress="74" skills="急救: 5|调度: 4"]
[fact: id="family-seen-hospital" value="true"]
[widget: battery, remove: 4]
周岚确认：体育馆在半小时前开始二次转移，河边道路很可能已经改变。
[state: value="取得可靠路线，并决定是否帮医院送出最后一箱药"]`, `[character_update: character_id="zhoulan-nurse" character="Zhoulan" role="Renhe Hospital nurse" detail="Eleven hours into her shift, organizing the last insulin transfer" lore="Lives near Riverbend School and knows the evacuation routes between the stadium and school" vitality="63" stress="74" skills="First Aid: 5|Dispatch: 4"]
[fact: id="family-seen-hospital" value="true"]
[widget: battery, remove: 4]
Zhoulan confirms the stadium began a second evacuation thirty minutes ago. The riverside roads may already have changed.
[state: value="Secure a reliable route and decide whether to carry the hospital’s last medicine"]`, ['答应把胰岛素冷藏箱送到山坡社区', '只拿一张防水纸图继续赶路', '请周岚先检查你和阿禾的伤势'], ['Carry the insulin cooler to Hillside Community', 'Take only a waterproof paper map and keep moving', 'Ask Zhoulan to check your and Ahe’s injuries']),

    ...stage(locale, [
      { zhMatch: ['胰岛素', '冷藏箱'], enMatch: ['insulin cooler'], zh: '你把蓝色冷藏箱固定在背包外侧。它让路更难走，却换来山坡社区会替你们开门的承诺。\n[inventory: action="add" item_id="insulin-cooler" item="胰岛素冷藏箱" count="1" rarity="rare" detail="医院最后一箱仍保持低温的胰岛素" effect="送达山坡社区可获得避雨、医疗和安全捷径；受热或浸水后失效" lore="周岚托付给仍要穿过东区的玩家" metrics="剩余低温: 3 小时|重量: 4.8 kg" image_prompt="single unbranded blue medical cooler strapped to a dark emergency backpack on wet hospital tile, no writing, object only, square"]\n[fact: id="hospital-helped" value="true"]', en: 'You strap the blue cooler outside your pack. It makes every step harder, but Hillside Community promises shelter and a safe shortcut.\n[inventory: action="add" item_id="insulin-cooler" item="Insulin Cooler" count="1" rarity="rare" detail="The hospital’s final batch of insulin still held below the safe temperature" effect="Delivering it to Hillside Community earns shelter, treatment and a safe shortcut; heat or floodwater ruins it" lore="Entrusted by Zhoulan to the player still crossing the east district" metrics="Cold time: 3 hours|Weight: 4.8 kg" image_prompt="single unbranded blue medical cooler strapped to a dark emergency backpack on wet hospital tile, no writing, object only, square"]\n[fact: id="hospital-helped" value="true"]', prompt: 'the same player protagonist securing a plain blue medical cooler to a small backpack while nurse Zhoulan watches, powerless hospital service corridor, 4:5 portrait, no labels, no writing, no text, no UI' },
      { zhMatch: ['防水纸图'], enMatch: ['waterproof paper map'], zh: '周岚把无字防水图折成手掌大小，用三枚颜色贴纸标出隧道、高架和山路。\n[inventory: action="add" item_id="waterproof-route-map" item="防水路线图" count="1" rarity="common" detail="没有街名、只用颜色和地形标记的东区应急图" effect="在一次路线危险前揭示较安全的替代路径" lore="周岚根据救护车最后可通行记录手绘" metrics="路线: 3 条|有效范围: 东区" image_prompt="single folded waterproof city route diagram with only abstract colored paths and no readable labels, wet concrete, object only, square"]\n[fact: id="direct-route-kept" value="true"]', en: 'Zhoulan folds an unlabeled waterproof map into your palm, marking tunnel, overpass and hill road with three colored stickers.\n[inventory: action="add" item_id="waterproof-route-map" item="Waterproof Route Map" count="1" rarity="common" detail="An east-district emergency diagram using only color and terrain marks" effect="Reveals one safer alternative before a route hazard" lore="Drawn from Zhoulan’s last ambulance access reports" metrics="Routes: 3|Coverage: east district" image_prompt="single folded waterproof city route diagram with only abstract colored paths and no readable labels, wet concrete, object only, square"]\n[fact: id="direct-route-kept" value="true"]', prompt: 'Zhoulan the distinct nurse placing a folded blank waterproof route diagram into the player protagonist hand, practical hospital corridor, 4:5 portrait, no letters, no numbers, no text, no UI', subject: 'others' },
      { zhMatch: ['检查', '伤势'], enMatch: ['check', 'injuries'], zh: '周岚清洗你掌心的裂口，又替阿禾重新固定脚踝。你们花了十分钟，却不再每一步都在流血。\n[widget: stamina, add: 12]\n[widget: time, remove: 8]\n[fact: id="hospital-treated" value="true"]', en: 'Zhoulan cleans the split in your palm and rewraps Ahe’s ankle. You spend ten minutes and stop leaving blood at every step.\n[widget: stamina, add: 12]\n[widget: time, remove: 8]\n[fact: id="hospital-treated" value="true"]', prompt: 'nurse Zhoulan bandaging the same player protagonist hand under a portable lamp while Ahe rests her ankle nearby, intimate disaster care, 4:5 portrait, no writing, no text, no UI' },
    ], `[fact: id="hospital-clue-confirmed" value="true"]
[clock: value="周二 · 00:58"]
[map_update: new_location="医院东门" connected_to="仁和医院 · 急诊入口" detail="三条离院路线都被雨幕吞没：积水隧道、受损高架和绕远山路" lore="这是到体育馆前最后一个仍能获得可靠路况的地点" facts="体育馆正在二次转移|河湾水位持续上升"]
[state: value="离开医院前，确认洪峰与家人路线的最后信息"]`, `[fact: id="hospital-clue-confirmed" value="true"]
[clock: value="Tuesday · 00:58"]
[map_update: new_location="Hospital East Gate" connected_to="Renhe Hospital · Emergency Entrance" detail="Three outbound routes disappear into rain: flooded tunnel, damaged overpass and the longer hill road" lore="The last point with reliable road information before the stadium" facts="The stadium is evacuating again|Riverbend water keeps rising"]
[state: value="Confirm the last flood and family information before leaving the hospital"]`, ['去屋顶天线听最新水位预报', '监听救援频道里的体育馆呼号', '把母亲语音交给周岚辨认背景'], ['Use the rooftop antenna for the latest water forecast', 'Monitor the rescue channel for the stadium call sign', 'Let Zhoulan identify the background in Mother’s message']),

    ...stage(locale, [
      { zhMatch: ['积水隧道'], enMatch: ['flooded tunnel'], zh: '隧道入口的水只到膝盖，深处却不断传来金属撞击。你用墙上水痕判断它正在快速上涨。\n[fact: id="route-choice" value="tunnel"]', en: 'Water reaches only your knees at the tunnel mouth, but metal keeps striking somewhere deeper. Marks on the wall show the level rising fast.\n[fact: id="route-choice" value="tunnel"]', prompt: 'the same player protagonist testing fast-rising water at the mouth of a dark urban tunnel, orange-jacket rider behind, flashlight reflections, 4:5 portrait, no signs, no writing, no text, no UI' },
      { zhMatch: ['受损高架'], enMatch: ['damaged overpass'], zh: '你们从维修梯登上高架。桥面没有水，却在余震中一段段错位，废车随坡度缓慢滑动。\n[fact: id="route-choice" value="overpass"]', en: 'You climb a maintenance ladder onto the overpass. The deck is dry but displaced by aftershocks, and abandoned cars slide slowly with the grade.\n[fact: id="route-choice" value="overpass"]', prompt: 'the same player protagonist climbing onto a rain-lashed damaged overpass as an empty car slides across broken lanes, Ahe below, 4:5 portrait, no readable signs, no text, no UI' },
      { zhMatch: ['绕山路', '山坡社区'], enMatch: ['Detour', 'Hillside'], zh: '山路多走二十分钟，但沿途亮着居民自接的暖色灯。阿禾说，灯还亮着就代表这条路有人维护。\n[fact: id="route-choice" value="hill-road"]', en: 'The hill road costs twenty minutes, but residents have strung warm lights along it. Ahe says a lit road is a road someone still maintains.\n[fact: id="route-choice" value="hill-road"]', prompt: 'the same player protagonist and orange-jacket rider climbing a steep rain-dark neighborhood road beneath improvised warm lights, grounded city disaster, 4:5 portrait, no writing, no text, no UI' },
    ], `[encounter: phase="warning" kind="路线正在失效" severity="3" outcome="active"]
[state: value="在路线完全中断前找到通过办法"]`, `[encounter: phase="warning" kind="The chosen route is failing" severity="3" outcome="active"]
[state: value="Find a way through before the route closes"]`, ['用随身工具测试最安全的落脚点', '让阿禾先行确认前路再互相接应', '放弃速度，沿最近的居民灯光撤回'], ['Use your tools to test the safest footing', 'Let Ahe scout ahead and relay each step', 'Give up speed and retreat toward the nearest resident lights']),

    ...stage(locale, [
      { zhMatch: ['工具', '落脚点'], enMatch: ['tools', 'footing'], zh: '你用伸缩杆、绳结和墙面刻度一点点试路。速度很慢，但你发现了真正承重的边缘。\n[skill_check: skill="灾后应变" dc="13" rolls="12" modifier="3" total="15" result="success"]\n[widget: stamina, remove: 8]', en: 'You test the route with an extension bar, rope knots and structural edges. Progress is slow, but you find the surfaces that still carry weight.\n[skill_check: skill="Disaster Response" dc="13" rolls="12" modifier="3" total="15" result="success"]\n[widget: stamina, remove: 8]', prompt: 'the same player protagonist probing a dangerous rain-dark urban crossing with a compact tool and safety rope, face visible, Ahe securing the line, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['阿禾先行', '接应'], enMatch: ['Ahe scout', 'relay'], zh: '阿禾把送餐时记路的本事用在断裂地形上，每到一个稳定点就回头打光。她没有替你走完，而是让你们都能继续。\n[reputation: npc="阿禾" action="trusted"]\n[fact: id="ahe-route-trusted" value="true"]', en: 'Ahe applies her delivery-route memory to the broken terrain, flashing her light from every stable point. She does not finish the crossing for you; she makes it possible for both of you.\n[reputation: npc="Ahe" action="trusted"]\n[fact: id="ahe-route-trusted" value="true"]', prompt: 'Ahe the distinct orange-jacket rider scouting a broken rain-soaked route and signaling back with a flashlight, player protagonist secured behind, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
      { zhMatch: ['放弃速度', '居民灯光'], enMatch: ['Give up speed', 'resident lights'], zh: '你们退向灯光，绕过最危险的一段。多出的路让时间变少，却把两名困在车里的老人一同带了出来。\n[widget: time, remove: 12]\n[fact: id="road-elders-helped" value="true"]', en: 'You retreat toward the lights and bypass the worst section. The detour costs time, but you bring two older residents out of a trapped car.\n[widget: time, remove: 12]\n[fact: id="road-elders-helped" value="true"]', prompt: 'the same player protagonist helping two older residents away from a trapped car toward warm neighborhood lights in heavy rain, 4:5 portrait, no signs, no text, no UI' },
    ], `[encounter: phase="resolution" kind="路线正在失效" severity="3" outcome="success"]
[fact: id="flood-route-crossed" value="true"]
[clock: value="周二 · 01:31"]
前方的体育馆灯全灭了。山腰社区却传来发电机启动失败的咳响。
[state: value="先确认山坡上仍可用的安全通路"]`, `[encounter: phase="resolution" kind="The chosen route is failing" severity="3" outcome="success"]
[fact: id="flood-route-crossed" value="true"]
[clock: value="Tuesday · 01:31"]
The stadium lights ahead are dark. On the hillside, a community generator coughs and fails.
[state: value="Confirm which safe passage on the hillside still works"]`, ['跟随水塔下仍亮着的三盏灯', '在塌陷药店前寻找居民标记', '爬上公交站棚观察山坡全貌'], ['Follow the three lights still burning below the water tower', 'Search for resident markers outside the collapsed pharmacy', 'Climb the bus shelter for a view across the hillside']),

    ...stage(locale, [
      { zhMatch: ['修社区发电机'], enMatch: ['Repair', 'generator'], zh: '你找到松脱的燃油管，阿禾把积水从启动机里引出。灯亮起来时，整条山路同时发出欢呼。\n[fact: id="hillside-generator-restored" value="true"]\n[widget: stamina, remove: 6]', en: 'You find a loose fuel line while Ahe drains water from the starter. When the lights return, the whole hillside cheers at once.\n[fact: id="hillside-generator-restored" value="true"]\n[widget: stamina, remove: 6]', prompt: 'the same player protagonist reconnecting a small community generator as warm apartment lights return through rain, Ahe assisting, humane disaster realism, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['直接穿过'], enMatch: ['Pass straight through'], zh: '你没有停下，只在路口留下医院仍开放的方向。一个男孩认出小宇的红书包，说他和母亲曾在这里问去体育馆的路。\n[fact: id="hillside-passed-fast" value="true"]', en: 'You do not stop, but leave the direction of the open hospital at the junction. A boy recognizes Xiaoyu’s red backpack and says he and his mother asked the way to the stadium.\n[fact: id="hillside-passed-fast" value="true"]', prompt: 'the same player protagonist moving quickly through a powerless hillside courtyard while a local boy points toward a dark stadium, Ahe distinct behind, 4:5 portrait, no readable signs, no text, no UI' },
      { zhMatch: ['冷藏箱', '临时诊所'], enMatch: ['cooler', 'temporary clinic'], zh: '临时诊所接过仍冰冷的药箱，立刻给三名患者安排注射。负责人让你们走只对居民开放的消防阶梯。\n[inventory: action="remove" item_id="insulin-cooler" item="胰岛素冷藏箱" count="1"]\n[fact: id="insulin-delivered" value="true"]\n[reputation: npc="山坡社区" action="helped"]', en: 'The temporary clinic receives the still-cold medicine and schedules three injections immediately. Its coordinator opens a resident-only fire stair for you.\n[inventory: action="remove" item_id="insulin-cooler" item="Insulin Cooler" count="1"]\n[fact: id="insulin-delivered" value="true"]\n[reputation: npc="Hillside Community" action="helped"]', prompt: 'clinic volunteers receiving a plain blue medical cooler from the same player protagonist under warm emergency lamps, grateful restrained emotion, 4:5 portrait, no labels, no writing, no text, no UI' },
    ], `[map_update: new_location="山坡社区" connected_to="医院东门" detail="层层住宅依山而建，居民用绳灯、对讲机和消防梯维持一条临时通路" lore="这里没有等待统一救援，而是把每户还能提供的能力拼成道路" facts="林岚和小宇经过这里|体育馆灯已熄灭"]
[fact: id="family-seen-hillside" value="true"]
社区广播突然提醒余震。头顶一面旧围墙开始向儿童临时教室倾斜。
[encounter: phase="warning" kind="余震与倾倒围墙" severity="4" outcome="active"]`, `[map_update: new_location="Hillside Community" connected_to="Hospital East Gate" detail="Homes climb the slope while residents maintain a temporary route with rope lights, radios and fire stairs" lore="No one waited for a single rescue plan; each household contributed one useful ability" facts="Lin Lan and Xiaoyu passed here|The stadium lights are out"]
[fact: id="family-seen-hillside" value="true"]
The community radio warns of an aftershock. An old wall begins leaning over the children’s temporary classroom.
[encounter: phase="warning" kind="Aftershock and falling wall" severity="4" outcome="active"]`, ['冲进教室带孩子从后门撤离', '用绳索拉住围墙争取时间', '让阿禾组织居民从消防梯接应'], ['Enter the classroom and lead children out the rear door', 'Use rope to hold the wall long enough', 'Have Ahe organize a fire-stair relay']),

    ...stage(locale, [
      { zhMatch: ['冲进教室'], enMatch: ['Enter the classroom'], zh: '你压低身体穿过落灰的教室，把最后两个孩子从卡住的后门推出去。墙在你身后倒下。\n[skill_check: skill="体能" dc="14" rolls="11" modifier="4" total="15" result="success"]\n[widget: stamina, remove: 12]\n[fact: id="hillside-children-safe" value="true"]', en: 'You stay low beneath falling dust and push the last two children through the jammed rear door. The wall collapses behind you.\n[skill_check: skill="Endurance" dc="14" rolls="11" modifier="4" total="15" result="success"]\n[widget: stamina, remove: 12]\n[fact: id="hillside-children-safe" value="true"]', prompt: 'the same player protagonist guiding two children through a jammed rear classroom door as dust falls during an aftershock, grounded rescue action, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['绳索拉住围墙'], enMatch: ['rope', 'hold the wall'], zh: '你把绳索绕过消防栓，用全身重量把围墙的倒向拉偏。孩子们从另一侧跑出时，绳子割破了手套。\n[skill_check: skill="灾后应变" dc="14" rolls="10" modifier="4" total="14" result="costly-success"]\n[widget: stamina, remove: 15]\n[fact: id="hillside-children-safe" value="true"]', en: 'You loop rope around a hydrant and use your full weight to pull the wall’s fall away from the classroom. The rope cuts through your gloves as the children escape.\n[skill_check: skill="Disaster Response" dc="14" rolls="10" modifier="4" total="14" result="costly-success"]\n[widget: stamina, remove: 15]\n[fact: id="hillside-children-safe" value="true"]', prompt: 'the same player protagonist straining on a safety rope to redirect a falling masonry wall while children escape, heavy rain and dust, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['阿禾组织', '消防梯'], enMatch: ['Ahe organize', 'fire-stair'], zh: '阿禾用送餐站调度口令把居民分成三段接力。她最后才下楼，怀里抱着一个一直没哭的孩子。\n[reputation: npc="阿禾" action="trusted"]\n[fact: id="ahe-community-leader" value="true"]\n[fact: id="hillside-children-safe" value="true"]', en: 'Ahe uses dispatch calls from her delivery days to form a three-part relay. She comes down last, carrying a child who never cried.\n[reputation: npc="Ahe" action="trusted"]\n[fact: id="ahe-community-leader" value="true"]\n[fact: id="hillside-children-safe" value="true"]', prompt: 'Ahe the distinct orange-jacket rider organizing residents along a fire stair and carrying a child to safety during an aftershock, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
    ], `[encounter: phase="resolution" kind="余震与倾倒围墙" severity="4" outcome="success"]
社区主任交给你一段对讲机录音：林岚问过“河湾学校屋顶还能不能接人”。
[fact: id="river-school-mentioned" value="true"]
[state: value="离开社区前，把对讲机录音和家人路线核对完整"]`, `[encounter: phase="resolution" kind="Aftershock and falling wall" severity="4" outcome="success"]
The community coordinator plays a radio recording: Lin Lan asked whether the roof at Riverbend School could still receive people.
[fact: id="river-school-mentioned" value="true"]
[state: value="Complete the radio clue and family route before leaving the community"]`, ['重听林岚提到河湾学校的完整录音', '吃一碗热饭再检查伤口', '把医院到学校的路线画给居民'], ['Replay the complete recording in which Lin Lan mentions the school', 'Eat one bowl of hot rice and check the injuries', 'Draw the hospital-to-school route for residents']),

    ...stage(locale, [
      { zhMatch: ['直下体育馆'], enMatch: ['directly', 'stadium'], zh: '你们用消防梯切过两层街区，十分钟后到达体育馆北门。门开着，里面却没有广播。\n[widget: time, add: 6]', en: 'The fire stair cuts across two blocks. Ten minutes later you reach the stadium north gate. It is open, but the announcements have stopped.\n[widget: time, add: 6]', prompt: 'the same player protagonist descending an exterior fire stair toward a dark rain-soaked city stadium, Ahe following, urgent 4:5 portrait, no readable signs, no text, no UI' },
      { zhMatch: ['姐姐', '社区名单'], enMatch: ['sister', 'community list'], zh: '名单里没有阿禾姐姐，但有一名伤员说她昨晚把药送去了河湾学校。阿禾第一次笑了一下：“那她还在做事。”\n[fact: id="ahe-sister-status-known" value="active-at-river-school"]\n[reputation: npc="阿禾" action="helped"]', en: 'Ahe’s sister is not on the list, but an injured resident saw her deliver medicine to Riverbend School. Ahe smiles for the first time: “Then she’s still doing something.”\n[fact: id="ahe-sister-status-known" value="active-at-river-school"]\n[reputation: npc="Ahe" action="helped"]', prompt: 'Ahe the distinct orange-jacket rider hearing hopeful news from an injured resident under warm rope lights, restrained relief, 4:5 portrait, blank list, no writing, no text, no UI', subject: 'others' },
      { zhMatch: ['短距对讲机'], enMatch: ['short-range radio'], zh: '主任借出最后一只备用对讲机，要求你们到学校后回报屋顶人数。\n[inventory: action="add" item_id="short-range-radio" item="短距对讲机" count="1" rarity="common" detail="只能覆盖约两公里、外壳已有裂纹的社区备用机" effect="在河湾区域建立一次稳定联络；浸水后失效" lore="山坡社区用来连接消防梯与临时诊所" metrics="范围: 2 km|电量: 31%" image_prompt="single worn unbranded handheld radio with cracked casing on wet dark fabric, blank controls, no writing, object only, square"]\n[fact: id="radio-promise" value="report-school-roof"]', en: 'The coordinator lends you the final backup radio and asks for a roof headcount once you reach the school.\n[inventory: action="add" item_id="short-range-radio" item="Short-range Radio" count="1" rarity="common" detail="A cracked community backup set with roughly two kilometers of range" effect="Creates one stable connection in the Riverbend area; floodwater destroys it" lore="Used to link the hillside fire stair and temporary clinic" metrics="Range: 2 km|Battery: 31%" image_prompt="single worn unbranded handheld radio with cracked casing on wet dark fabric, blank controls, no writing, object only, square"]\n[fact: id="radio-promise" value="report-school-roof"]', prompt: 'a community coordinator handing a small blank handheld radio to the same player protagonist beneath rope lights, practical disaster scene, 4:5 portrait, no letters, no text, no UI' },
    ], `[map_update: new_location="东区体育馆 · 北门" connected_to="山坡社区" detail="临时床铺仍温热，地上留下匆忙转移的水痕，主场灯和广播都已停止" lore="官方避难点曾聚集三千人，却在水位预报改变后分散转移" facts="人群已经离开|河湾学校是可能目的地"]
[clock: value="周二 · 02:09"]
[state: value="在空体育馆里找到家人留下的下一条线索"]`, `[map_update: new_location="East District Stadium · North Gate" connected_to="Hillside Community" detail="Temporary cots remain warm and wet tracks show a rushed transfer; arena lights and announcements are dead" lore="The official shelter held three thousand people before a changed flood forecast forced a dispersed evacuation" facts="The crowd has left|Riverbend School is a likely destination"]
[clock: value="Tuesday · 02:09"]
[state: value="Find the family’s next trace inside the empty stadium"]`, ['去登记台找小宇的红书包记录', '沿看台水迹检查最后撤离路线', '爬到广播室恢复一次供电'], ['Search registration for Xiaoyu’s red backpack', 'Follow wet tracks along the last evacuation route', 'Restore one burst of power in the broadcast room']),

    ...stage(locale, [
      { zhMatch: ['红书包记录'], enMatch: ['red backpack'], zh: '登记台没有姓名，只留着一张儿童用药勾选卡。背面夹着林岚常用的银色发卡。\n[inventory: action="add" item_id="linlan-hairclip" item="林岚的银色发卡" count="1" rarity="rare" detail="一枚边缘磨亮的旧发卡，仍缠着一根湿发" effect="向见过林岚的人确认身份；无法指示方向" lore="林岚在体育馆登记台留下，作为家人一定会认出的记号" metrics="主人: 林岚|状态: 完好" image_prompt="single plain silver hairclip beside a blank emergency check card on wet stadium desk, no writing, object only, square"]\n[fact: id="family-left-stadium-known" value="true"]', en: 'Registration has no names, only a child medicine card. Lin Lan’s familiar silver hairclip is pinned behind it.\n[inventory: action="add" item_id="linlan-hairclip" item="Lin Lan’s Silver Hairclip" count="1" rarity="rare" detail="An old hairclip polished at the edges with one wet strand still caught in it" effect="Confirms Lin Lan’s identity to a witness; gives no direction by itself" lore="Left at stadium registration as a sign her family would recognize" metrics="Owner: Lin Lan|Condition: intact" image_prompt="single plain silver hairclip beside a blank emergency check card on wet stadium desk, no writing, object only, square"]\n[fact: id="family-left-stadium-known" value="true"]', prompt: 'the same player protagonist finding a familiar silver hairclip behind a blank card at an abandoned stadium registration desk, emotional close action, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['看台水迹'], enMatch: ['wet tracks'], zh: '水迹从看台一路通向南侧装卸门。一个用粉笔画出的简单屋顶符号重复出现，旁边有小宇鞋底缺角的印纹。\n[fact: id="family-left-stadium-known" value="true"]\n[fact: id="xiaoyu-track-confirmed" value="true"]', en: 'Wet tracks lead from the stands to the south loading gate. A simple roof symbol repeats beside the chipped tread of Xiaoyu’s shoe.\n[fact: id="family-left-stadium-known" value="true"]\n[fact: id="xiaoyu-track-confirmed" value="true"]', prompt: 'the same player protagonist kneeling beside wet shoe tracks and a simple abstract roof mark on stadium concrete, flashlight beam, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['广播室', '供电'], enMatch: ['broadcast room', 'power'], zh: '你让备用电源工作了四十秒。最后一段自动录音只有一句清楚：南区转移队改去河湾学校。\n[widget: battery, remove: 5]\n[fact: id="family-left-stadium-known" value="true"]\n[fact: id="stadium-broadcast-restored" value="true"]', en: 'You keep backup power alive for forty seconds. One line of the final recording is clear: the south group diverted to Riverbend School.\n[widget: battery, remove: 5]\n[fact: id="family-left-stadium-known" value="true"]\n[fact: id="stadium-broadcast-restored" value="true"]', prompt: 'the same player protagonist restarting a compact backup console in a dark stadium broadcast room while one indicator glows, face visible, 4:5 portrait, blank controls, no writing, no text, no UI' },
    ], `体育馆南门外，一辆最后撤离的公交车陷在迅速上涨的水里。车上还有六个人；通往河湾学校的步行桥就在它后面。
[encounter: phase="warning" kind="被困公交与上涨洪水" severity="4" outcome="active"]
[state: value="先判断公交周围水流和可用救援工具"]`, `Outside the south gate, the final evacuation bus is stuck in fast-rising water with six people aboard. The footbridge to Riverbend School lies behind it.
[encounter: phase="warning" kind="Trapped bus and rising floodwater" severity="4" outcome="active"]
[state: value="Assess the current and available rescue tools around the bus"]`, ['检查南门水深和公交倾斜角度', '收集体育馆剩余绳索与破窗锤', '询问最后一名保安公交上还有谁'], ['Check water depth and the bus angle', 'Gather the stadium rope and emergency hammer', 'Ask the last guard who remains aboard']),

    ...stage(locale, [
      { zhMatch: ['牵引绳'], enMatch: ['tow rope'], zh: '你固定牵引绳，让阿禾在岸上报节奏。第六个人上岸时，水已经没过车灯。\n[widget: stamina, remove: 16]\n[fact: id="stadium-bus-rescued" value="true"]', en: 'You anchor the tow rope while Ahe calls the rhythm from shore. By the time the sixth person reaches land, water covers the headlights.\n[widget: stamina, remove: 16]\n[fact: id="stadium-bus-rescued" value="true"]', prompt: 'the same player protagonist chest-deep in floodwater guiding evacuees along a tow rope from a trapped city bus, Ahe anchoring on shore, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['砸开公交后窗'], enMatch: ['Break the rear window'], zh: '你用破窗锤打开后窗，把乘客送上步行桥。公交被水推走时，没有一个人还在里面。\n[skill_check: skill="灾后应变" dc="15" rolls="13" modifier="3" total="16" result="success"]\n[fact: id="stadium-bus-rescued" value="true"]', en: 'You open the rear window with an emergency hammer and move everyone onto the footbridge. When the bus floats away, no one remains inside.\n[skill_check: skill="Disaster Response" dc="15" rolls="13" modifier="3" total="16" result="success"]\n[fact: id="stadium-bus-rescued" value="true"]', prompt: 'the same player protagonist using an emergency hammer at the rear window of a flooded bus while evacuees climb onto a footbridge, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['呼叫山坡社区'], enMatch: ['Call Hillside'], zh: '你报出公交位置后继续前进。对讲机里很快传来社区接单的回应，但那六个人能否及时获救，暂时没有答案。\n[fact: id="bus-location-shared" value="true"]\n[widget: battery, remove: 3]', en: 'You report the bus location and keep moving. The radio quickly confirms a hillside team is responding, but the six people’s outcome remains unknown.\n[fact: id="bus-location-shared" value="true"]\n[widget: battery, remove: 3]', prompt: 'the same player protagonist speaking into a small radio while moving across a rain-lashed footbridge, trapped bus behind and Ahe alongside, 4:5 portrait, no writing, no text, no UI' },
    ], `[encounter: phase="resolution" kind="被困公交与上涨洪水" severity="4" outcome="success"]
[map_update: new_location="南区步行桥" connected_to="东区体育馆 · 北门" detail="桥面在雨中摇晃，前方通向河湾学校，后方体育馆已经进水" lore="最后一批体育馆撤离者曾从这里分散到学校和高地住宅" facts="家人去往河湾学校|体育馆路线即将封闭"]
[fact: id="family-location-confirmed" value="riverbend-school"]
[clock: value="周二 · 02:47"]
[state: value="核对河湾水势，选择进入学校街区的最后路线"]`, `[encounter: phase="resolution" kind="Trapped bus and rising floodwater" severity="4" outcome="success"]
[map_update: new_location="South District Footbridge" connected_to="East District Stadium · North Gate" detail="The bridge sways in rain toward Riverbend School while floodwater enters the stadium behind" lore="The final stadium evacuees dispersed from here toward the school and higher apartments" facts="The family went to Riverbend School|The stadium route is closing"]
[fact: id="family-location-confirmed" value="riverbend-school"]
[clock: value="Tuesday · 02:47"]
[state: value="Read the Riverbend flood and choose the final route into the school district"]`, ['把纸图与眼前水流重新核对', '询问公交获救者学校方向', '用对讲机呼叫河湾学校屋顶'], ['Recheck the paper map against the visible current', 'Ask a rescued bus passenger for the school route', 'Call the Riverbend School roof by radio']),

    ...stage(locale, [
      { zhMatch: ['主街追赶'], enMatch: ['main street'], zh: '主街最快，也最暴露。你踩着还没被水吞没的中央隔离带前进，远处看见小宇同款红书包。', en: 'The main street is fastest and most exposed. You advance along the last dry median and spot a red backpack like Xiaoyu’s in the distance.', prompt: 'the same player protagonist running along the last dry median of a flooded city street toward a distant red backpack, Ahe following, 4:5 portrait, no signs, no writing, no text, no UI' },
      { zhMatch: ['居民楼连廊'], enMatch: ['apartment walkways'], zh: '居民把床单结成扶手，让你们穿过三栋楼的二层连廊。每户门口都放着一盏向外照的灯。', en: 'Residents knot bedsheets into handrails across three second-floor walkways. Every apartment points one lamp outward.', prompt: 'the same player protagonist crossing improvised second-floor apartment walkways with bedsheet handrails above floodwater, warm doorway lamps, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['应急灯', '后门'], enMatch: ['emergency lights', 'rear gate'], zh: '水上的应急灯原来绑在一条旧皮划艇旁。你们推着它前进，顺便带上了一名走失的女孩。\n[fact: id="lost-child-accompanied" value="true"]', en: 'The emergency lights are tied beside an old kayak. You push it through the water and take a lost girl with you.\n[fact: id="lost-child-accompanied" value="true"]', prompt: 'the same player protagonist pushing a small unbranded kayak with emergency lights through a flooded residential lane while Ahe comforts a lost girl, 4:5 portrait, no writing, no text, no UI' },
    ], `河湾学校后门被漂来的家具堵住。楼上有人敲击栏杆，三短两长——这是林岚教给家人的求救节奏。
[fact: id="family-signal-heard" value="true"]
[encounter: phase="confrontation" kind="堵塞校门与加速水流" severity="4" outcome="active"]
[state: value="穿过最后一个街区，抵达发出求救节奏的校门"]`, `Drifting furniture blocks the rear gate. Someone above strikes the railing in three short beats and two long—the distress rhythm Lin Lan taught the family.
[fact: id="family-signal-heard" value="true"]
[encounter: phase="confrontation" kind="Blocked school gate and accelerating current" severity="4" outcome="active"]
[state: value="Cross the final block and reach the gate sending the distress rhythm"]`, ['清理堵塞排水口降低街角水位', '护送一户居民到学校外梯', '翻过操场围栏绕到后门'], ['Clear a blocked drain to lower the corner current', 'Escort one household to the school exterior stair', 'Cross the playground fence to reach the rear gate']),

    ...stage(locale, [
      { zhMatch: ['移开堵门'], enMatch: ['Move the bookcases'], zh: '你和阿禾把书柜一件件推入水流，再拉住门不让它回撞。最后一张桌子移开时，门内有人伸手接住你。\n[widget: stamina, remove: 13]', en: 'You and Ahe push the bookcases into the current one by one, then hold the gate against the rebound. When the last desk moves, a hand reaches from inside for you.\n[widget: stamina, remove: 13]', prompt: 'the same player protagonist and orange-jacket rider forcing a blocked school gate open against floodwater and drifting furniture, 4:5 portrait, blank walls, no writing, no text, no UI' },
      { zhMatch: ['爬到二楼'], enMatch: ['Climb', 'second-floor'], zh: '你沿体育馆排水管爬到二楼，踢开一扇卡住的窗。阿禾留在下方把绳索绑给其他人。\n[skill_check: skill="体能" dc="15" rolls="12" modifier="4" total="16" result="success"]\n[widget: stamina, remove: 10]', en: 'You climb a gym drainpipe and force open a jammed second-floor window. Ahe stays below to tie the rope for everyone else.\n[skill_check: skill="Endurance" dc="15" rolls="12" modifier="4" total="16" result="success"]\n[widget: stamina, remove: 10]', prompt: 'the same player protagonist climbing a rain-slick school gym drainpipe toward an open second-floor window, face visible, Ahe securing rope below, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['手机闪光'], enMatch: ['phone light'], zh: '你用三短两长的闪光回应。楼上立刻垂下一根由窗帘和跳绳接成的绳索，但手机只剩最后一点电。\n[widget: battery, remove: 8]\n[fact: id="family-signal-answered" value="true"]', en: 'You answer with three short flashes and two long. A rope made from curtains and jump ropes drops immediately, but the phone is nearly empty.\n[widget: battery, remove: 8]\n[fact: id="family-signal-answered" value="true"]', prompt: 'the same player protagonist signaling upward with a blank glowing phone as an improvised rope drops from a flooded school window, 4:5 portrait, no writing, no text, no UI' },
    ], `[encounter: phase="resolution" kind="堵塞校门与加速水流" severity="4" outcome="success"]
[map_update: new_location="河湾学校 · 二楼" connected_to="南区步行桥" detail="一楼已进水，二楼教室住着四十七名转移者，屋顶等待最后救援" lore="普通学校被居民、教师和学生改造成河湾最后一个垂直避难点" facts="家人信号来自楼上|屋顶仍有人"]
[fact: id="river-school-reached" value="true"]
[clock: value="周二 · 03:18"]
[state: value="在学校里找到林岚和小宇，并准备屋顶营救"]`, `[encounter: phase="resolution" kind="Blocked school gate and accelerating current" severity="4" outcome="success"]
[map_update: new_location="Riverbend School · Second Floor" connected_to="South District Footbridge" detail="The first floor is flooded, forty-seven evacuees occupy classrooms and the roof awaits final rescue" lore="Residents, teachers and students turned an ordinary school into Riverbend’s last vertical shelter" facts="The family signal came from above|People remain on the roof"]
[fact: id="river-school-reached" value="true"]
[clock: value="Tuesday · 03:18"]
[state: value="Find Lin Lan and Xiaoyu inside the school and prepare the roof rescue"]`, ['逐间教室喊家里的约定暗号', '询问照顾伤员的学生志愿者', '沿三短两长的敲击声上楼'], ['Call the family’s private phrase through each classroom', 'Ask the student volunteers caring for injuries', 'Follow the three-short two-long knocks upstairs']),

    ...stage(locale, [
      { zhMatch: ['约定暗号'], enMatch: ['private phrase'], zh: '你只喊了一遍“冰箱里还有半个西瓜”。走廊尽头立刻传来小宇带哭腔的回答：“早就坏了。”', en: 'You call once: “There’s half a watermelon in the fridge.” Xiaoyu answers through tears from the far corridor: “It went bad already.”', prompt: 'the same player protagonist calling through a dim crowded school corridor as a teenage boy answers from the far end, emotional reunion about to happen, 4:5 portrait, blank walls, no writing, no text, no UI' },
      { zhMatch: ['学生志愿者'], enMatch: ['student volunteers'], zh: '学生志愿者记得林岚一直替孩子们擦干头发。她和小宇刚把最后一名老人扶上屋顶。', en: 'A student volunteer remembers Lin Lan drying children’s hair. She and Xiaoyu just helped the last older evacuee to the roof.', prompt: 'a distinct student volunteer pointing up a dark school stairwell while the same player protagonist listens, crowded evacuation classroom behind, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
      { zhMatch: ['敲击声上楼'], enMatch: ['knocks upstairs'], zh: '你跟着敲击声冲上最后一段楼梯。转角先出现小宇的红书包，然后是林岚苍白却清醒的脸。', en: 'You follow the knocks up the final stairs. Xiaoyu’s red backpack appears around the landing first, then Lin Lan’s pale but alert face.', prompt: 'the same player protagonist reaching a school stair landing as a teenage boy with a red backpack and his mother appear above, emotional realistic reunion, 4:5 portrait, no writing, no text, no UI' },
    ], `[character_update: character_id="lin-lan-mother" character="林岚" role="母亲" detail="左肩扭伤，仍在帮屋顶居民维持秩序" lore="最后语音里提醒玩家不要走河边；一路留下只有家人能认出的记号" vitality="68" stress="61" skills="照料: 5|判断: 4"]
[character_update: character_id="xiaoyu-brother" character="小宇" role="弟弟" detail="右膝擦伤，背着红书包，协助记录屋顶人数" lore="十六岁；在害怕时仍坚持把老人送上屋顶" vitality="74" stress="72" skills="记路: 3|无线电: 3"]
[fact: id="family-found" value="true"]
你终于抱住他们，但学校与高地之间的连桥已经断了。屋顶还有十九个人，救援船只能靠近一次。
[state: value="在立刻行动前，让这次团聚真正发生"]`, `[character_update: character_id="lin-lan-mother" character="Lin Lan" role="Mother" detail="Left shoulder strained, still maintaining order among roof evacuees" lore="Warned the player away from the river in the final message and left signs only family would recognize" vitality="68" stress="61" skills="Care: 5|Judgment: 4"]
[character_update: character_id="xiaoyu-brother" character="Xiaoyu" role="Younger brother" detail="Right knee scraped, red backpack on, helping count people on the roof" lore="Sixteen; frightened and still insisted on helping older evacuees upstairs" vitality="74" stress="72" skills="Wayfinding: 3|Radio: 3"]
[fact: id="family-found" value="true"]
You finally hold them, but the bridge toward high ground is gone. Nineteen people remain on the roof and the rescue boat can approach only once.
[state: value="Let the reunion happen before immediate action resumes"]`, ['安静坐一分钟，听家人的呼吸', '让小宇讲完他们一路发生的事', '问林岚为什么最后去了河湾学校'], ['Sit quietly for one minute and hear the family breathe', 'Let Xiaoyu finish telling what happened on their route', 'Ask why Lin Lan ultimately chose Riverbend School']),

    ...stage(locale, [
      { zhMatch: ['检查小宇', '肩膀'], enMatch: ['Check Xiaoyu', 'shoulder'], zh: '你替小宇重新包扎，又把林岚的手臂固定在胸前。她小声说：“我知道你会来，但不想你为这句话死在路上。”\n[widget: stamina, add: 5]\n[fact: id="family-treated" value="true"]', en: 'You rewrap Xiaoyu’s knee and secure Lin Lan’s arm. She whispers, “I knew you would come. I never wanted that sentence to kill you on the road.”\n[widget: stamina, add: 5]\n[fact: id="family-treated" value="true"]', prompt: 'the same player protagonist gently bandaging a teenage brother beside their injured mother in a dark school stairwell, intimate family relief, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['核对屋顶人数'], enMatch: ['Count the roof'], zh: '你和小宇逐个核对：十九人、两名不能行走、三段承重绳、一只破损皮划艇。数字让恐惧第一次变成问题。\n[fact: id="roof-count-confirmed" value="true"]', en: 'You and Xiaoyu count: nineteen people, two unable to walk, three load-bearing ropes and one damaged kayak. Numbers turn fear into a problem for the first time.\n[fact: id="roof-count-confirmed" value="true"]', prompt: 'the same player protagonist and teenage brother inspecting three ropes and a damaged kayak among roof evacuees before dawn rain, 4:5 portrait, no written numbers, no text, no UI' },
      { zhMatch: ['阿禾', '姐姐', '药箱'], enMatch: ['Ahe', 'sister', 'medicine'], zh: '阿禾在器材室找到姐姐的橙色急救袋和一张空白胶带记号。她确认姐姐已经随第一艘船去高地接应。\n[inventory: action="add" item_id="ahe-sister-firstaid" item="橙色急救袋" count="1" rarity="rare" detail="装有止血带、保温毯和两支应急镇痛药的旧骑手急救袋" effect="在最终转移中稳定两名重伤者；使用后耗尽" lore="阿禾姐姐送药到学校后留下，胶带记号表明她已安全前往高地" metrics="可稳定重伤者: 2|药品: 一次" image_prompt="single unbranded orange first-aid pouch with thermal blanket and blank tape mark on school floor, no writing, object only, square"]\n[fact: id="ahe-sister-status-known" value="safe-at-high-ground"]', en: 'Ahe finds her sister’s orange first-aid pouch and a blank tape mark in the equipment room. It confirms her sister took the first boat to organize high-ground reception.\n[inventory: action="add" item_id="ahe-sister-firstaid" item="Orange First-aid Pouch" count="1" rarity="rare" detail="An old rider kit with tourniquet, thermal blanket and two emergency pain doses" effect="Stabilizes two seriously injured people during final transfer; then empty" lore="Left after Ahe’s sister delivered medicine to the school; her tape mark confirms she reached high ground" metrics="Critical patients: 2|Medicine: one use" image_prompt="single unbranded orange first-aid pouch with thermal blanket and blank tape mark on school floor, no writing, object only, square"]\n[fact: id="ahe-sister-status-known" value="safe-at-high-ground"]', prompt: 'Ahe the distinct orange-jacket rider finding her sister orange first-aid pouch in a dark school equipment room, relief and exhaustion, 4:5 portrait, no labels, no writing, no text, no UI', subject: 'others' },
    ], `[clock: value="周二 · 03:46"]
远处救援船的灯第一次出现。水流会让它无法停靠，你们必须给船一个明确的接近点。
[encounter: phase="warning" kind="洪峰前最后一次靠船" severity="5" outcome="active"]
[state: value="在建立连接前，完成屋顶的最后准备"]`, `[clock: value="Tuesday · 03:46"]
The rescue boat’s light appears for the first time. The current will prevent it from stopping; the roof must provide one clear approach point.
[encounter: phase="warning" kind="Final boat approach before the crest" severity="5" outcome="active"]
[state: value="Finish the roof preparations before creating the connection"]`, ['根据水位估算救援船靠近时间', '把十九个人按行动能力分组', '用课桌加固屋顶最薄弱的边缘'], ['Estimate the boat approach time from the water level', 'Group the nineteen people by mobility', 'Reinforce the weakest roof edge with desks']),

    ...stage(locale, [
      { zhMatch: ['双重信标'], enMatch: ['double beacon'], zh: '你把手机绑在对讲机旁，按三短两长交替发光和呼叫。林岚最后的私人语音成了全屋顶都听见的定位节奏。\n[widget: battery, remove: 10]\n[fact: id="voice-shared-with-rescue" value="true"]', en: 'You bind the phone beside the radio and alternate three-short two-long light and calls. Lin Lan’s private message becomes the positioning rhythm heard by the whole roof.\n[widget: battery, remove: 10]\n[fact: id="voice-shared-with-rescue" value="true"]', prompt: 'the same player protagonist raising a blank glowing phone and handheld radio above a flooded school roof as a rescue boat turns toward the signal, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['三段绳索', '长索'], enMatch: ['three ropes', 'long line'], zh: '你、小宇和阿禾把三种绳结在一起。第一次落空，第二次被船员接住，屋顶和船终于在水面上连成一条线。\n[fact: id="roof-line-secured" value="true"]\n[widget: stamina, remove: 8]', en: 'You, Xiaoyu and Ahe join three different ropes. The first throw misses; a crew member catches the second, and roof and boat finally become one line across the water.\n[fact: id="roof-line-secured" value="true"]\n[widget: stamina, remove: 8]', prompt: 'the same player protagonist throwing a long joined rope from a flooded school roof toward a rescue boat while family and Ahe anchor it, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['皮划艇', '水上引导'], enMatch: ['kayak', 'floating guide'], zh: '你们把应急灯绑在破损皮划艇上，让它沿绳漂向船。船长看懂了这条不会说话的路线。\n[fact: id="kayak-guide-launched" value="true"]', en: 'You attach emergency lights to the damaged kayak and send it down the rope. The captain understands the route that cannot speak.\n[fact: id="kayak-guide-launched" value="true"]', prompt: 'a damaged kayak with small blank emergency lights sliding along a rope from a school roof toward a rescue boat in pre-dawn floodwater, people silhouetted but no focal face, 4:5 portrait, no writing, no text, no UI', subject: 'environment' },
    ], `船只能先接八个人。就在第一批准备下绳时，另一栋低楼传来敲击声：那里还有一家三口，水已经到窗沿。
[encounter: phase="confrontation" kind="一次靠船与两个屋顶" severity="5" outcome="active"]
[state: value="在洪峰前决定第一批名额与另一栋楼的命运"]`, `The boat can take only eight people first. As the first group reaches the rope, knocking sounds from a lower roof: a family of three is trapped with water at the windows.
[encounter: phase="confrontation" kind="One boat and two roofs" severity="5" outcome="active"]
[state: value="Decide the first passengers and the other roof’s fate before the crest"]`, ['让伤员与孩子先走，自己留下组织第二趟', '让林岚和小宇先上船，随后引船去低楼', '把另一栋楼的位置交给船长，集中撤离本屋顶'], ['Send injured people and children first and stay for the second run', 'Put Lin Lan and Xiaoyu aboard, then guide the boat to the lower roof', 'Give the lower roof location to the captain and evacuate this roof first']),

    ...stage(locale, [
      { zhMatch: ['自己留下', '第二趟'], enMatch: ['stay', 'second run'], zh: '你把两名伤员、五个孩子和一名照料者送下绳，自己留在屋顶。林岚没有劝你，只把发卡重新别回头上。\n[fact: id="final-choice-stay" value="true"]\n[fact: id="children-first" value="true"]', en: 'You send two injured people, five children and one caregiver down the line, then remain on the roof. Lin Lan does not argue; she simply pins her hairclip back in place.\n[fact: id="final-choice-stay" value="true"]\n[fact: id="children-first" value="true"]', prompt: 'the same player protagonist holding the roof rope while children and injured evacuees descend first, mother Lin Lan behind with her own distinct face, emotional pre-dawn rain, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['林岚和小宇先上船'], enMatch: ['Lin Lan and Xiaoyu aboard'], zh: '你亲手把小宇和林岚送上船，又要求船长立刻绕向低楼。小宇抓着你的手，直到绳索拉直才松开。\n[fact: id="family-aboard-first" value="true"]\n[fact: id="other-roof-rescue-attempted" value="true"]', en: 'You put Xiaoyu and Lin Lan aboard and ask the captain to turn immediately toward the lower roof. Xiaoyu holds your hand until the rope pulls taut.\n[fact: id="family-aboard-first" value="true"]\n[fact: id="other-roof-rescue-attempted" value="true"]', prompt: 'the same player protagonist helping teenage brother and mother with distinct faces onto a rescue boat from a school roof, hands separating as rope tightens, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['集中撤离本屋顶'], enMatch: ['evacuate this roof first'], zh: '你把低楼的准确位置交给船长，要求他回程优先寻找。此刻你选择先把眼前十九个人变成确定的生还者。\n[fact: id="other-roof-location-shared" value="true"]\n[fact: id="roof-evacuation-prioritized" value="true"]', en: 'You give the captain the lower roof’s exact position and make it first priority on the return. For now, you turn the nineteen people before you into certain survivors.\n[fact: id="other-roof-location-shared" value="true"]\n[fact: id="roof-evacuation-prioritized" value="true"]', prompt: 'the same player protagonist pointing the rescue captain toward a lower flooded roof while organizing evacuees on the school roof, decisive restrained disaster drama, 4:5 portrait, no writing, no text, no UI' },
    ], `[fact: id="final-rescue-decided" value="true"]
[encounter: phase="resolution" kind="一次靠船与两个屋顶" severity="5" outcome="costly-success"]
[clock: value="周二 · 04:21"]
第一缕晨光照到高地水塔。你们已经找到彼此，却还要决定这趟“回家”最后意味着什么。
[state: value="完成最后一次不可撤销的选择"]`, `[fact: id="final-rescue-decided" value="true"]
[encounter: phase="resolution" kind="One boat and two roofs" severity="5" outcome="costly-success"]
[clock: value="Tuesday · 04:21"]
First light reaches the high-ground water tower. You found one another, but must still decide what “home” means at the end of this road.
[state: value="Make the final irreversible choice"]`, ['和家人一起登上最后一趟船', '留下帮助船长寻找仍亮着灯的窗户', '把手机交给小宇记录这条救援路线'], ['Board the final boat with your family', 'Stay and help the captain search every lit window', 'Give Xiaoyu the phone to preserve this rescue route']),

    ...stage(locale, [
      { zhMatch: ['屋顶天线'], enMatch: ['rooftop antenna'], zh: '屋顶天线只清楚了半分钟：洪峰提前，河湾低地四点后将失去船只通行条件。\n[fact: id="crest-time-confirmed" value="04:00"]', en: 'The rooftop antenna clears for thirty seconds: the crest is early, and boats will lose access to low Riverbend after four.\n[fact: id="crest-time-confirmed" value="04:00"]', prompt: 'the same player protagonist adjusting a small rooftop emergency antenna above a dark hospital in heavy rain, clear face, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['救援频道', '体育馆呼号'], enMatch: ['rescue channel', 'stadium call'], zh: '救援频道里，体育馆呼号已经改为“撤空”，南组最后目的地被截断在“河湾”两个音节之后。\n[fact: id="stadium-evacuated-radio" value="true"]', en: 'On the rescue channel the stadium call sign changes to “empty.” The south group destination cuts off immediately after “Riverbend.”\n[fact: id="stadium-evacuated-radio" value="true"]', prompt: 'Ahe the distinct orange-jacket rider listening to a blank handheld receiver beside rooftop antenna cables in hard rain, hospital roof at night, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
      { zhMatch: ['母亲语音', '辨认背景'], enMatch: ['Mother', 'background'], zh: '周岚认出语音末尾不是体育馆广播，而是河湾学校每小时测试一次的旧铃。你的家人可能比记录更早改变了路线。\n[fact: id="school-bell-recognized" value="true"]', en: 'Zhoulan recognizes the final sound not as a stadium announcement but as Riverbend School’s hourly emergency bell. Your family may have changed routes earlier than the records show.\n[fact: id="school-bell-recognized" value="true"]', prompt: 'nurse Zhoulan listening closely to a blank phone held by the same player protagonist in a powerless hospital stairwell, realization, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
    ], `你现在知道，速度不是抽象数字：四点以后，学校屋顶可能再也等不到船。
[fact: id="flood-deadline-understood" value="true"]
[state: value="选择穿过东区的路线，在洪峰前抵达体育馆"]`, `You now know speed is not an abstract number: after four, the school roof may no longer receive a boat.
[fact: id="flood-deadline-understood" value="true"]
[state: value="Choose a route across the east district and reach the stadium before the crest"]`, ['走积水隧道，争取最快抵达', '爬上受损高架避开洪水', '绕山路经过山坡社区'], ['Take the flooded tunnel for the fastest route', 'Climb the damaged overpass above the flood', 'Detour through Hillside Community']),

    ...stage(locale, [
      { zhMatch: ['三盏灯'], enMatch: ['three lights'], zh: '三盏灯分别守着消防梯、临时诊所和发电机房。你终于看懂这不是装饰，而是一套居民路标。\n[fact: id="hillside-light-code" value="true"]', en: 'The three lights mark the fire stair, temporary clinic and generator room. They are not decoration but a resident route code.\n[fact: id="hillside-light-code" value="true"]', prompt: 'the same player protagonist reading three warm blank route lights across a rain-dark hillside neighborhood, face visible, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['塌陷药店'], enMatch: ['collapsed pharmacy'], zh: '药店卷帘门上贴着三段无字反光带，指向仍可通行的后巷。阿禾说这正是姐姐的做法。\n[fact: id="ahe-sister-route-found" value="true"]', en: 'Three blank reflective strips on the collapsed pharmacy shutter point into a passable rear alley. Ahe says this is exactly her sister’s method.\n[fact: id="ahe-sister-route-found" value="true"]', prompt: 'Ahe the distinct orange-jacket rider recognizing three blank reflective tape strips on a collapsed pharmacy shutter, rain and relief, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
      { zhMatch: ['公交站棚'], enMatch: ['bus shelter'], zh: '从站棚顶看，积水正在把低路切成孤岛，只有社区消防梯仍连续通向体育馆。\n[fact: id="hillside-safe-passage-seen" value="true"]', en: 'From the bus shelter roof, floodwater divides the low road into islands. Only the community fire stair remains continuous toward the stadium.\n[fact: id="hillside-safe-passage-seen" value="true"]', prompt: 'the same player protagonist standing atop a blank bus shelter and surveying a flooded hillside route of connected fire stairs, 4:5 portrait, no signs, no writing, no text, no UI' },
    ], `[state: value="穿过山坡社区，确认体育馆最后一批人去了哪里"]`, `[state: value="Cross Hillside Community and learn where the stadium’s last evacuees went"]`, ['去修社区发电机换取可靠路况', '直接穿过社区赶往体育馆', '先把医院冷藏箱送到临时诊所'], ['Repair the community generator for reliable road news', 'Pass straight through toward the stadium', 'Deliver the hospital cooler to the temporary clinic']),

    ...stage(locale, [
      { zhMatch: ['重听林岚'], enMatch: ['Replay', 'recording'], zh: '完整录音里，林岚先问学校屋顶，再问有没有人能带腿伤的孩子走高路。她一直在替小宇找下一步。\n[fact: id="mother-planned-school-route" value="true"]', en: 'In the complete recording Lin Lan asks first about the school roof, then whether anyone can take an injured child along the high route. She was always planning Xiaoyu’s next step.\n[fact: id="mother-planned-school-route" value="true"]', prompt: 'the same player protagonist listening to a handheld radio recording beside warm community lights, quiet emotional realization, Ahe secondary, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['热饭', '伤口'], enMatch: ['hot rice', 'injuries'], zh: '一碗热饭让手不再发抖。居民替你换掉浸湿的绷带，也提醒你别把回家变成倒在家门前。\n[widget: stamina, add: 9]\n[widget: time, remove: 5]', en: 'A bowl of hot rice stops your hands shaking. Residents replace the soaked bandage and warn you not to turn going home into collapsing at the door.\n[widget: stamina, add: 9]\n[widget: time, remove: 5]', prompt: 'the same player protagonist eating a small bowl of hot rice while a resident replaces a wet hand bandage under warm emergency light, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['路线画给居民'], enMatch: ['route for residents'], zh: '你把医院仍开放、旧市场已疏散和三条危险路画成无字色块。主任立即把它复制到每部对讲机旁。\n[fact: id="route-shared-with-community" value="true"]', en: 'You turn the open hospital, evacuated market and three dangerous roads into an unlabeled color diagram. The coordinator copies it beside every radio.\n[fact: id="route-shared-with-community" value="true"]', prompt: 'the same player protagonist drawing an abstract color-only route diagram for hillside residents around a table of radios, 4:5 portrait, no letters, no numbers, no text, no UI' },
    ], `[state: value="抵达已经熄灯的体育馆，确认家人是否转往河湾学校"]`, `[state: value="Reach the dark stadium and confirm whether the family moved to Riverbend School"]`, ['沿消防阶梯直下体育馆北门', '先陪阿禾确认她姐姐是否在社区名单上', '向主任借一只短距对讲机'], ['Take the fire stair directly to the stadium north gate', 'First help Ahe check whether her sister is on the community list', 'Borrow a short-range radio from the coordinator']),

    ...stage(locale, [
      { zhMatch: ['公交倾斜'], enMatch: ['bus angle'], zh: '公交正在向深水侧缓慢倾斜，最多还能稳住五分钟；车尾离步行桥反而更近。\n[fact: id="bus-rear-exit-best" value="true"]', en: 'The bus is leaning toward deeper water and may remain stable for five minutes. Its rear is actually closer to the footbridge.\n[fact: id="bus-rear-exit-best" value="true"]', prompt: 'the same player protagonist measuring the lean of a half-flooded city bus from a safe barrier in heavy rain, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['剩余绳索', '破窗锤'], enMatch: ['rope', 'emergency hammer'], zh: '你找到一卷牵引绳和一把破窗锤。两件东西都能救人，但必须先决定从哪一侧接近。\n[inventory: action="add" item_id="stadium-rescue-kit" item="体育馆救援工具" count="1" rarity="common" detail="一卷湿牵引绳和一把带腕带的破窗锤" effect="可执行一次公交水上救援；使用后留在现场" lore="体育馆最后一名保安从器材柜取出" metrics="绳长: 28 m|破窗锤: 1" image_prompt="single wet tow rope and unbranded emergency window hammer on dark stadium concrete, no writing, object only, square"]', en: 'You find one coil of tow rope and an emergency hammer. Either can save people, but you must choose the approach side first.\n[inventory: action="add" item_id="stadium-rescue-kit" item="Stadium Rescue Tools" count="1" rarity="common" detail="A wet tow rope and wrist-strapped emergency hammer" effect="Enables one bus water rescue; remains at the scene afterward" lore="Retrieved by the stadium’s last guard" metrics="Rope: 28 m|Hammer: 1" image_prompt="single wet tow rope and unbranded emergency window hammer on dark stadium concrete, no writing, object only, square"]', prompt: 'the same player protagonist lifting a wet tow rope and blank emergency hammer from an open stadium equipment cage, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['最后一名保安'], enMatch: ['last guard'], zh: '保安确认车上有两名儿童、一名腿伤者和三名工作人员。司机已经用安全带把门固定住。\n[fact: id="bus-passengers-known" value="six-mixed-mobility"]', en: 'The guard confirms two children, one person with a leg injury and three staff remain aboard. The driver has secured the door with seatbelts.\n[fact: id="bus-passengers-known" value="six-mixed-mobility"]', prompt: 'the last stadium guard with his own distinct face briefing the same player protagonist beside a flooded bus, urgent practical realism, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
    ], `[state: value="决定如何处理被困公交，同时保住去河湾学校的时间"]`, `[state: value="Deal with the trapped bus without losing the route to Riverbend School"]`, ['用体育馆牵引绳把人逐个拉回', '砸开公交后窗让人转移到步行桥', '呼叫山坡社区，让你们先追家人'], ['Use the stadium tow rope to pull people back one by one', 'Break the rear window and move people onto the footbridge', 'Call Hillside Community and continue after your family']),

    ...stage(locale, [
      { zhMatch: ['纸图', '水流'], enMatch: ['paper map', 'current'], zh: '纸图上的低路已经完全失效，但三栋居民楼连廊仍与学校后街相连。\n[fact: id="riverbend-walkway-route" value="true"]', en: 'Every low route on the paper map has failed, but three apartment walkways still connect to the school’s rear street.\n[fact: id="riverbend-walkway-route" value="true"]', prompt: 'the same player protagonist comparing an abstract blank waterproof route map with visible flood currents from a footbridge, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['公交获救者'], enMatch: ['rescued bus passenger'], zh: '一名获救教师说，最后的学校队伍沿主街走，孩子们每隔一个路口就留下红色布条。\n[fact: id="school-red-cloth-trail" value="true"]', en: 'A rescued teacher says the final school group used the main street, leaving a red cloth strip at every junction.\n[fact: id="school-red-cloth-trail" value="true"]', prompt: 'a rescued teacher with a distinct face pointing down a flooded street while the same player protagonist listens on a footbridge, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
      { zhMatch: ['呼叫河湾学校'], enMatch: ['Call', 'School roof'], zh: '对讲机里先是静电，随后有人回了三短两长。那不是正式呼号，是你们家的求救节奏。\n[fact: id="family-radio-signal" value="true"]\n[widget: battery, remove: 2]', en: 'Static answers first, then three short tones and two long. It is not an official call sign; it is your family distress rhythm.\n[fact: id="family-radio-signal" value="true"]\n[widget: battery, remove: 2]', prompt: 'the same player protagonist hearing a family rhythm from a blank handheld radio on a rain-lashed footbridge, emotional close shot, 4:5 portrait, no writing, no text, no UI' },
    ], `[state: value="沿河湾街区抵达学校，在洪峰前找到家人"]`, `[state: value="Cross Riverbend and find the family before the crest"]`, ['沿主街追赶学校转移队', '穿居民楼连廊避开低洼路段', '跟随水面上的应急灯去学校后门'], ['Follow the school transfer group along the main street', 'Use apartment walkways above the low streets', 'Follow emergency lights across the water to the school rear gate']),

    ...stage(locale, [
      { zhMatch: ['排水口'], enMatch: ['blocked drain'], zh: '你和阿禾拖开堵住排水口的塑料棚，街角水位短暂下降，露出通往校门的台阶。\n[widget: stamina, remove: 6]\n[fact: id="school-corner-drained" value="true"]', en: 'You and Ahe pull a plastic awning off the drain. The corner water drops long enough to expose steps toward the school gate.\n[widget: stamina, remove: 6]\n[fact: id="school-corner-drained" value="true"]', prompt: 'the same player protagonist and distinct orange-jacket rider clearing a storm drain as school steps emerge from floodwater, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['护送一户居民'], enMatch: ['Escort one household'], zh: '你把一家三口护送到学校外梯。父亲指出，三短两长来自体育馆屋顶方向。\n[fact: id="riverbend-family-helped" value="true"]', en: 'You escort a family of three to the school exterior stair. The father points out that three-short two-long comes from the gym roof.\n[fact: id="riverbend-family-helped" value="true"]', prompt: 'the same player protagonist guiding a family of three through waist-deep water toward a school exterior stair, Ahe behind, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['操场围栏'], enMatch: ['playground fence'], zh: '你翻过围栏，从器材棚顶绕到后门。校舍上方再次传来熟悉的敲击节奏。\n[fact: id="school-rear-gate-reached" value="true"]', en: 'You cross the fence and use the equipment shed roof to reach the rear gate. The familiar knocking rhythm comes again from above.\n[fact: id="school-rear-gate-reached" value="true"]', prompt: 'the same player protagonist crossing a rain-slick playground fence toward a flooded school rear gate, face visible, 4:5 portrait, no writing, no text, no UI' },
    ], `[state: value="进入河湾学校，回应家人的求救信号"]`, `[state: value="Enter Riverbend School and answer the family signal"]`, ['合力移开堵门的书柜和桌子', '从体育馆外墙爬到二楼窗户', '用手机闪光回应，让楼上放下绳索'], ['Move the bookcases and desks blocking the gate', 'Climb the gym wall to a second-floor window', 'Answer with the phone light and ask for a rope']),

    ...stage(locale, [
      { zhMatch: ['安静坐一分钟'], enMatch: ['Sit quietly'], zh: '你们靠在楼梯间墙上，谁都没有说话。小宇的呼吸从急促慢慢变稳；这一分钟没有推进救援，却把你们重新变成一家人。\n[fact: id="family-reunion-breathed" value="true"]', en: 'You sit against the stairwell wall without speaking. Xiaoyu’s breathing slows. The minute advances no rescue plan, but makes you a family again.\n[fact: id="family-reunion-breathed" value="true"]', prompt: 'the same player protagonist sitting quietly between mother and teenage brother with distinct faces in a dim school stairwell, exhausted reunion, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['小宇讲完'], enMatch: ['Xiaoyu finish'], zh: '小宇讲完了医院、体育馆和一路帮助他们的人。他最后说：“我不是在等你救，我也带妈妈走了这么远。”\n[fact: id="xiaoyu-agency-heard" value="true"]', en: 'Xiaoyu finishes the story of the hospital, stadium and every person who helped. Then he says, “I wasn’t just waiting for rescue. I brought Mom this far too.”\n[fact: id="xiaoyu-agency-heard" value="true"]', prompt: 'teenage Xiaoyu with his own distinct face telling the route story to the player protagonist and mother in a school stairwell, quiet pride, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
      { zhMatch: ['为什么最后去了'], enMatch: ['why Lin Lan'], zh: '林岚说她没有“选对”学校，只是在每个路口都选了还有人在互相照看的方向。你走的也是同一条路。\n[fact: id="mother-route-principle" value="mutual-care"]', en: 'Lin Lan says she did not “choose the correct school.” At every junction she chose the direction where people were still caring for one another. You followed the same road.\n[fact: id="mother-route-principle" value="mutual-care"]', prompt: 'mother Lin Lan with her own distinct face explaining her route choice to the same player protagonist and teenage son in a dark school stairwell, 4:5 portrait, no writing, no text, no UI', subject: 'others' },
    ], `[state: value="把团聚变成真正的脱险计划"]`, `[state: value="Turn reunion into an actual escape plan"]`, ['先检查小宇的伤和林岚的肩膀', '立刻核对屋顶人数与可用绳索', '让阿禾去找她姐姐留下的药箱'], ['Check Xiaoyu’s knee and Lin Lan’s shoulder first', 'Count the roof and inspect every usable rope', 'Have Ahe search for the medicine her sister left']),

    ...stage(locale, [
      { zhMatch: ['估算救援船'], enMatch: ['Estimate the boat'], zh: '你用水线上升速度算出船只只有一个七分钟窗口。错过以后，水流会把它推向高架桥墩。\n[fact: id="boat-window-known" value="seven-minutes"]', en: 'From the rising waterline you calculate a seven-minute boat window. After that, the current will push it into the overpass piers.\n[fact: id="boat-window-known" value="seven-minutes"]', prompt: 'the same player protagonist comparing rising flood marks with a distant rescue boat from a school roof, face visible, 4:5 portrait, no written numbers, no text, no UI' },
      { zhMatch: ['按行动能力分组'], enMatch: ['Group the nineteen'], zh: '小宇记录分组：能自行下绳、需要搀扶、必须平躺。每个人第一次知道自己该站在哪里。\n[fact: id="roof-groups-ready" value="true"]', en: 'Xiaoyu records three groups: independent, assisted and flat transfer. For the first time, everyone knows where to stand.\n[fact: id="roof-groups-ready" value="true"]', prompt: 'teenage Xiaoyu with his own distinct face organizing roof evacuees into mobility groups while the player protagonist checks ropes, 4:5 portrait, no written lists, no text, no UI', subject: 'others' },
      { zhMatch: ['加固屋顶'], enMatch: ['Reinforce', 'roof edge'], zh: '你们把课桌腿卡进女儿墙裂口，临时形成一个能承受绳索侧拉的锚点。\n[widget: stamina, remove: 5]\n[fact: id="roof-anchor-reinforced" value="true"]', en: 'You wedge desk legs into the cracked parapet, creating an anchor that can survive the rope’s sideways pull.\n[widget: stamina, remove: 5]\n[fact: id="roof-anchor-reinforced" value="true"]', prompt: 'the same player protagonist bracing a cracked school roof edge with plain desk frames before a rescue rope transfer, pre-dawn rain, 4:5 portrait, no writing, no text, no UI' },
    ], `[state: value="建立屋顶与救援船之间的唯一安全连接"]`, `[state: value="Create the one safe connection between the roof and the rescue boat"]`, ['用手机和对讲机组成双重信标', '把三段绳索接成长索抛向船头', '放下破损皮划艇作为水上引导'], ['Combine phone and radio into a double beacon', 'Join the three ropes and throw one long line to the bow', 'Lower the damaged kayak as a floating guide']),

    ...stage(locale, [
      { zhMatch: ['一起登上', '最后一趟船'], enMatch: ['Board the final boat'], zh: '你最后一个跨进船舱。林岚把额头靠在你肩上，小宇第一次不再回头数屋顶。城市没有恢复，但你们终于不用再隔着一条路。\n[fact: id="final-intent" value="go-home-together"]\n[fact: id="true-ending-started" value="true"]\n[true_ending: reason="玩家完成屋顶转移，选择与家人一起离开洪水区，并让一路帮助过的人、付出的代价和未完成的承诺共同决定天亮后的生活。"]', en: 'You step into the boat last. Lin Lan rests her forehead on your shoulder, and Xiaoyu stops counting roofs behind him. The city is not repaired, but there is no longer a road between you.\n[fact: id="final-intent" value="go-home-together"]\n[fact: id="true-ending-started" value="true"]\n[true_ending: reason="After completing the roof transfer, the player leaves the flood zone with family; every person helped, cost paid and promise left open shapes life after dawn."]', prompt: 'the same player protagonist boarding a rescue boat last beside mother and teenage brother with distinct faces as dawn reaches a flooded city, intimate hopeful realism, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['留下帮助', '亮着灯'], enMatch: ['Stay', 'lit window'], zh: '你让家人先去高地，自己和船长折回雨里。林岚没有说“早点回家”，只说：“下一次，让我们一起去找你。”\n[fact: id="final-intent" value="search-the-lit-windows"]\n[fact: id="true-ending-started" value="true"]\n[true_ending: reason="玩家确认家人安全后，选择继续寻找仍亮灯的窗户；家人、阿禾和社区留下的关系决定这次离开是牺牲、承诺还是新的共同生活。"]', en: 'You send your family to high ground and turn back into the rain with the captain. Lin Lan does not say, “Come home soon.” She says, “Next time, we come looking for you together.”\n[fact: id="final-intent" value="search-the-lit-windows"]\n[fact: id="true-ending-started" value="true"]\n[true_ending: reason="After securing the family, the player continues toward lit windows; relationships with family, Ahe and the community decide whether this departure becomes sacrifice, promise or a shared new life."]', prompt: 'the same player protagonist turning a rescue boat back toward isolated lit windows while family watches safely from another boat at dawn, emotional grounded disaster cinema, 4:5 portrait, no writing, no text, no UI' },
      { zhMatch: ['手机交给小宇'], enMatch: ['Give Xiaoyu the phone'], zh: '你把只剩一格电的手机交给小宇。里面有林岚最后的语音、一路拍下的路口和所有被帮助者的位置。他接过的不是纪念品，而是一张下一次能更快回家的图。\n[inventory: action="remove" item_id="phone" item="手机" count="1"]\n[fact: id="final-intent" value="pass-on-the-route"]\n[fact: id="true-ending-started" value="true"]\n[true_ending: reason="玩家把承载家人语音与救援路线的手机交给小宇，让私人寻亲记录成为下一次灾难中可以帮助更多人的公共路线。"]', en: 'You give Xiaoyu the phone with one bar left. It holds Lin Lan’s last message, every junction and every person helped. He receives not a souvenir, but a map that could bring someone home faster next time.\n[inventory: action="remove" item_id="phone" item="Phone" count="1"]\n[fact: id="final-intent" value="pass-on-the-route"]\n[fact: id="true-ending-started" value="true"]\n[true_ending: reason="The player gives Xiaoyu the phone containing the family message and rescue route, turning a private search record into a public route that may help others in the next disaster."]', prompt: 'the same player protagonist placing a nearly dark blank phone into teenage brother hands while mother and Ahe watch on a rescue boat at dawn, emotional close scene, 4:5 portrait, no writing, no text, no UI' },
    ], '', '', ['查看这次旅程留下的结局', '听完家人的最后一段话', '从新的选择重新开始'], ['See the ending shaped by this journey', 'Hear the family’s final words', 'Begin again from a new choice']),
  ]
}
